### ISSUE TITLE
Not working on Kodi 17.6

### ISSUE THREAD

**Issue by dbuteau** [robweber/cronxbmc#16]
I've installed the released package
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'module' object has no attribute 'makedir'
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/service.cronxbmc/service.py", line 6, in <module>
CronService().runProgram()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 155, in __init__
self.manager = CronManager()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 22, in __init__
self.jobs = self._readCronFile()
File "/home/osmc/.kodi/addons/service.cronxbmc/resources/lib/cron.py", line 93, in _readCronFile
xbmcvfs.makedir(xbmc.translatePath(utils.data_dir()))
AttributeError: 'module' object has no attribute 'makedir'
http://mirrors.kodi.tv/docs/python-docs/14.x-helix/xbmcvfs.html
-->End of Python script error report<--
```

If i understand well the code and if i believe this link: 
http://mirrors.kodi.tv/docs/python-docs/14.x-helix/xbmcvfs.html

the correct syntax is 
```
xbmcvfs.mkdir()
```

And changed the code on my Kodi, and yup it worked

**Comment by robweber** [comment]
What version are you using? Looking at line 93 of the cron.py file that isn't even part of the _readCronFile function any longer. It's actually line [115](https://github.com/robweber/cronxbmc/blob/master/resources/lib/cron.py#L115) and it looks like that call has been [fixed for a while](https://github.com/robweber/cronxbmc/commit/85f51d386202cb5dc55baf7e9b2d2034aab63494#diff-d520764767ed1214ab6f58ffe46d7422) unless I'm missing something. 

Did you download yours right from this repo? Thanks for reporting, if there is an issue somewhere else in the code with that function I'd like to take care of it.

**Comment by dbuteau** [comment]
i've downloaded the zip from the release tab here. Tagged "jarvis" version the only one available in release tab (can't found this addon on superrepo or others repo)

**Comment by robweber** [comment]
Gotcha - forgot that tag existed.......

You can still pull from master, the xbmc.python version is still compatible with Jarvis in that file. It has a few more fixes. I'll create a new tag so there is no confusion.

**Comment by dbuteau** [comment]
sorry for confusion, believed that zip was the last stable release. Anyway, thank for your answer :)
